apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: yzs-pod-gpu-metrics-exporter
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: pod-gpu-metrics-exporter
      name: pod-gpu-metrics-exporter
    spec:
      nodeSelector:
        hardware-type: NVIDIAGPU
      containers:
        - image: yzs981130/pod-gpu-metrics-exporter:latest
          name: yzs-pod-nvidia-gpu-metrics-exporter
          ports:
            - name: gpu-metrics
              containerPort: 9400
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: pod-gpu-resources
              readOnly: true
              mountPath: /var/lib/kubelet/pod-resources
            - name: device-metrics
              readOnly: true
              mountPath: /run/prometheus
        - image: nvidia/dcgm-exporter:1.4.6
          name: nvidia-dcgm-exporter
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: device-metrics
              mountPath: /run/prometheus

      volumes:
        - name: pod-gpu-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
        - name: device-metrics
          emptyDir:
            medium: Memory
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: pod-gpu-metrics-svc
  annotations:
    prometheus.io/port: "9400"
    prometheus.io/path: "/gpu/metrics"
    prometheus.io/scrape: "true"
  name: pod-gpu-metrics-svc
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 9400
      targetPort: 9400
      nodePort: 30400
  selector:
    app: pod-gpu-metrics-exporter
